version: "3.7"

services:
  calendar:
    build: .
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    build: ./postgres/
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: user
      POSTGRES_DB: postgres

volumes:
  postgres_data:
    driver: local
